<?php
    $tabs = $block->prepareTabsData();
    if (!$tabs) {
        return;
    }

    $htmlId = uniqid('swissup-easytabs-');
    $tabsLayoutType = $block->getTabsLayoutType();
?>
<div class="product info detailed">
<?php if ($block->hasToolbar()): ?>
    <div class="tabs-toolbar" data-mage-init='{"Swissup_Easytabs/js/tabs-toolbar": {}}'>
    <?php foreach ($tabs as $_index => $_tab): ?>
        <a class="tabs-toolbar-item"
            data-action="activate-tab"
            href="#<?= $_tab['alias'] ?>">
            <?= /* @escapeNotVerified */ $_tab['title'] ?>
        </a>
    <?php endforeach ?>
    </div>
<?php endif ?>

    <div id="<?= $htmlId ?>"
        class="product data items <?= $tabsLayoutType ?>"
        data-content-type="easytabs"
        data-mage-init='{"Swissup_Easytabs/js/tabs": <?= $block->getInitOptions() ?>}'
    >
        <?php if ($tabsLayoutType == 'collapsed'): ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/collapsed.phtml')); ?>
        <?php elseif ($tabsLayoutType == 'expanded') : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/expanded.phtml')); ?>
        <?php elseif ($tabsLayoutType == 'accordion') : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/accordion.phtml')); ?>
        <?php else : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/default.phtml')); ?>
        <?php endif ?>
    </div>
</div>
<?php if ($listenProductTabs = $block->getListenProductTabs()): ?>
<script type="text/x-magento-init">
{
    "#<?= $htmlId ?>": {
        "Swissup_Easytabs/js/tabs-updater": <?= json_encode([
            'aliases' => $listenProductTabs,
            'url' => $block->getAjaxUrl('tab_alias')
        ]); ?>
    }
}
</script>
<?php endif ?>
