<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php
    $tabs = $block->prepareTabsData();
    if (!$tabs) {
        return;
    }

    $htmlId = uniqid('swissup-easytabs-');
    $tabsLayoutType = $block->getTabsLayoutType();
?>
<div class="product info detailed">
<?php if ($block->hasToolbar()): ?>
    <div class="tabs-toolbar" data-mage-init='{"Swissup_Easytabs/js/tabs-toolbar": {}}'>
    <?php foreach ($tabs as $_index => $_tab): ?>
        <a class="tabs-toolbar-item"
            data-action="activate-tab"
            href="#<?= $escaper->escapeHtmlAttr($_tab['alias']) ?>">
            <?= $escaper->escapeHtml($_tab['title'], ['span']) ?>
        </a>
    <?php endforeach ?>
    </div>
<?php endif ?>

    <div id="<?= $escaper->escapeHtmlAttr($htmlId) ?>"
        class="product data items <?= $escaper->escapeHtmlAttr($tabsLayoutType) ?>"
        data-content-type="easytabs"
        data-mage-init='{"Swissup_Easytabs/js/tabs": <?= /* @noEscape */ $block->getInitOptions() ?>}'
    >
        <?php if ($tabsLayoutType == 'collapsed'): ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/collapsed.phtml')); ?>
        <?php elseif ($tabsLayoutType == 'expanded') : ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/expanded.phtml')); ?>
        <?php elseif ($tabsLayoutType == 'accordion') : ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/accordion.phtml')); ?>
        <?php else : ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/default.phtml')); ?>
        <?php endif ?>
    </div>
</div>
<?php if ($listenProductTabs = $block->getListenProductTabs()): ?>
<script type="text/x-magento-init">
{
    "#<?= $escaper->escapeJs($htmlId) ?>": {
        "Swissup_Easytabs/js/tabs-updater": <?= /* @noEscape */ json_encode([
            'aliases' => $listenProductTabs,
            'url' => $block->getAjaxUrl('tab_alias')
        ]); ?>
    }
}
</script>
<?php endif ?>
