<?php
    $tabs = [];
    foreach ($block->getTabs() as $_index => $_tab) {
        if (!($childHtml = $block->getChildHtml($_tab['alias']))
            || $block->isEmptyString($childHtml)) {

            continue;
        }
        $_tab['child_html'] = $childHtml;
        $_tab['title'] = $block->getTabTitle($_tab);

        $tabs[$_index] = $_tab;
    }
?>
<div class="product info detailed">
    <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
        <?php foreach ($tabs as $_index => $_tab) : ?>
            <?php
                $html = $_tab['child_html'];
                $alias = $_tab['alias'];
                $label = $_tab['title'];
            ?>
            <div class="data item title"
                aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                <a class="data switch"
                   tabindex="-1"
                   data-toggle="switch"
                   href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                   id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                    <?php /* @escapeNotVerified */ echo $label; ?>
                </a>
            </div>
            <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                <?php /* @escapeNotVerified */ echo $html; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
