<?php $attributes = new \Magento\Framework\DataObject(); ?>
<?php foreach ($tabs as $_index => $_tab) : ?>
    <?php
        $alias = $block->escapeHtmlAttr($_tab['alias']);
        $isAjax = $_tab['is_ajax'] ?? false;
        $attributes->setData(array_filter([
            'class' => 'data switch',
            'id' => "tab-label-{$alias}-title",
            'data-toggle' => 'switch',
            'data-ajaxurl' => ($isAjax ? $block->getAjaxUrl($alias) : false)
        ]));
    ?>
    <div id="tab-label-<?= $alias ?>"
        class="data item title"
        aria-controls="<?= $alias; ?>"
        data-role="collapsible"
    >
        <a <?= $attributes->serialize() ?> tabindex="-1" href="#<?= $alias ?>">
            <?= /* @escapeNotVerified */ $_tab['title'] ?>
        </a>
    </div>
    <div id="<?= $alias; ?>" class="data item content" data-role="content">
        <?= /* @escapeNotVerified */ $isAjax ? '' : $_tab['child_html'] ?>
    </div>
<?php endforeach; ?>
