<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php
    $attributes = new \Magento\Framework\DataObject();
    $isFirst = true;
?>
<?php foreach ($tabs as $_tab) : ?>
    <?php
        $alias = $escaper->escapeHtmlAttr($_tab['alias']);
        $attributes->setData(array_filter([
            'class' => 'data switch',
            'id' => "tab-label-{$alias}-title",
            'data-toggle' => 'switch',
            'data-ajaxurl' => ($_tab['is_ajax'] ? $block->getAjaxUrl($_tab['alias']) : false)
        ]));
    ?>
    <div id="tab-label-<?= /* @noEscape */ $alias ?>"
        class="data item title<?= $isFirst ? ' active' : '' ?>"
        aria-labelledby="tab-label-<?= /* @noEscape */ $alias ?>-title"
        aria-controls="<?= /* @noEscape */ $alias ?>"
        data-role="collapsible"
    >
        <a <?= /* @noEscape */ $attributes->serialize() ?> tabindex="-1" href="#<?= /* @noEscape */ $alias ?>">
            <?= $escaper->escapeHtml($_tab['title'], ['span']) ?>
        </a>
    </div>
    <div id="<?= /* @noEscape */ $alias ?>" class="data item content" data-role="content">
        <?= /* @noEscape */ $_tab['is_ajax'] ? '' : $_tab['child_html'] ?>
    </div>
<?php $isFirst = false; endforeach; ?>
