<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php $attributes = new \Magento\Framework\DataObject(); ?>
<?php foreach ($tabs as $_index => $_tab) : ?>
    <?php
        $alias = $_tab['alias'];
        $isAjax = $_tab['is_ajax'] ?? false;
        $attributes->setData(array_filter([
            'class' => 'title',
            'id' => "tab-label-{$alias}-title",
            'data-toggle' => 'switch',
            'data-ajaxurl' => $isAjax ? $block->getAjaxUrl($alias) : false
        ]));
    ?>
    <div id="tab-label-<?= $escaper->escapeHtmlAttr($alias) ?>"
        class="data item title active"
        aria-controls="<?= $escaper->escapeHtmlAttr($alias); ?>"
        data-role="collapsible"
    >
        <h2 <?= /* @noEscape */ $attributes->serialize() ?>><?= $escaper->escapeHtml($_tab['title'], ['span']) ?></h2>
    </div>
    <div id="<?= $escaper->escapeHtmlAttr($alias); ?>" class="data item content" data-role="content">
        <?= /* @noEscape */ $isAjax ? '' : $_tab['child_html'] ?>
    </div>
<?php endforeach; ?>
