<?php
    $attributeCode = $block->getAttributeCode();
    $product = $block->getProduct();
    if (!$attributeCode || !$product) {
        return;
    }
    $attribute = $product->getResource()->getAttribute($attributeCode);
    if (!$attribute) {
        return;
    }
    $content = $attribute->getFrontend()->getValue($product);
    if (empty($content)) {
        return;
    }
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <div class="product attibute">
    <?php  
        if($attribute->getFrontend()->getInputType() == 'file'){
            $file = $block->getUrl().'pub/media/catalog/product/file/'.$content;
            echo '<a href="'.$file.'" target="_blank" title="'.$content.'">'.$content.'</a>';
        }else{
            echo $_helper->productAttribute(
            $block->getProduct(), $content, $attributeCode
            );    
        }
    ?>
    </div>
