<?php
    $htmlId = uniqid('ui-component-');
?>
<style type="text/css">
[data-index=widget_options] input[type="number"] {
    max-width: 8rem;
}
[data-index=widget_options] .action-select-wrap .action-menu._active {
    overflow: hidden;
}
[data-index=widget_options] .action-select-wrap .action-menu._active .admin__action-multiselect-menu-inner {
    max-height: 20em;
}
</style>

<script type="text/javascript">
    require([
        'Magento_Ui/js/lib/view/utils/async',
        'Magento_Ui/js/core/app'
    ], function ($, app) {
        app(<?= $block->getJsLayout() ?>);
        $.async({
            selector: '#<?= $htmlId ?>'
        }, (el) => {
           $(el).applyBindings();
        });
    });
</script>

<div id="<?= $htmlId ?>" class="admin__field-control control">
<!-- ko scope: '<?= $block->getScopeName() ?>' -->
    <!-- ko template: getTemplate() --><!-- /ko -->
<!-- /ko -->
</div>
