<?php
    $attributes = new \Magento\Framework\DataObject();
?>
<div role="tablist">
    <?php foreach ($tabs as $_tab) : ?>
        <?php
            $alias = $_tab['alias'];
            $label = $_tab['title'];
            $attributes->setData([
                'class' => 'data switch',
                'id' => "tab-label-{$alias}-title",
                'data-toggle' => 'switch',
            ]);
            if ($_tab['is_ajax']) {
                $attributes->setData(
                    'data-ajaxurl',
                    $block->getAjaxUrl($alias)
                );
            }
        ?>
        <div class="data item title"
            aria-labelledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
            aria-controls="<?= /* @escapeNotVerified */ $alias; ?>"
            data-role="collapsible"
            id="tab-label-<?= /* @escapeNotVerified */ $alias ?>"
        >
            <a <?= $attributes->serialize() ?>
                tabindex="-1"
                href="#<?= $alias ?>">
                <?= /* @escapeNotVerified */ $label ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<?php foreach ($tabs as $_tab) : ?>
    <div class="data item content"
        id="<?= /* @escapeNotVerified */ $_tab['alias'] ?>"
        data-role="content"
    >
        <?= /* @escapeNotVerified */ $_tab['is_ajax'] ? '' : $_tab['child_html'] ?>
    </div>
<?php endforeach; ?>